### ISSUE TITLE
Build adjustments

### ISSUE THREAD

**Issue by ScriptedAlchemy** [module-federation/utilities#3]
Lets keep rollup since it works great for libraries, but we should adjust the config. 

1) consider disable tree shaking on library so all exports are retained - let the consumer's compiler do the tree shaking
2) lets use perserveModules to reflect the source directory structure in the build output
3) commonJS output as well as ESM output? might be useful for max compatibility
4) lets adjust the `src` directory structure in prep for supporting more utilities
4.1) We should create `src/runtime` and `src/buildtime` directories so we can organize various utils depending on if they are tools that can be leveraged in/on webpack config and plugin side as well as tools that are intended to be used within the application when its executing 
5) Lets not create this just yet, but it might be a good idea to make a `src/server` directory for SSR-specific tools when using module federation in a node-like environment.

**Comment by alex-vukov** [comment]
The suggested improvements were implemented and merged into the main branch.
